package com.POG.julindang.admin.domain;


import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.*;

import java.util.Date;

@Getter
@Builder
@DynamoDBTable(tableName = "inquiry")
@AllArgsConstructor
@NoArgsConstructor
@Setter // Setters are used in aws-dynamodb-sdk
public class Inquiry {
    @DynamoDBHashKey(attributeName = "inquiry_id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String sender;

    @DynamoDBAttribute
    private String category;

    @DynamoDBAttribute
    private String question;

    @DynamoDBAttribute
    private String answer;

    @DynamoDBAttribute
    private Date created_at;


}
